#ifndef MYDLL_EXAMPLE_GLOBAL_H
#define MYDLL_EXAMPLE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MYDLL_EXAMPLE_LIBRARY)
#  define MYDLL_EXAMPLESHARED_EXPORT Q_DECL_EXPORT
#else
#  define MYDLL_EXAMPLESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MYDLL_EXAMPLE_GLOBAL_H
